<div id="extra">
    <div class="inner">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <h3>WHY CHOOSE MEGAMITCH?</h3>
                    <p class="text-justify">
                        Nunc euismod lobortis massa, id sollicitudin augue auctor vel. Integer ornare sollicitudin turpis vitae vestibulum. Curabitur faucibus ullamcorper lorem sed egestas. Pellentesque laoreet auctor eros, et consectetur eros auctor eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tortor nisi, egestas eget molestie tincidunt, tempus sed justo. Vestibulum ultricies auctor varius. Fusce consequat tincidunt dui, ac adipiscing turpis adipiscing pulvinar. Aliquam erat volutpat. Vivamus eleifend rhoncus nulla in laoreet.
                    </p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-sm-4">
                            <h3>Other Links</h3>
                            <ul>
                                <li>Our Team</li>
                                <li>Our Office</li>
                                <li>Careers</li>
                            </ul>
                        </div>
                        <div class="col-sm-8">
                            <h3>Contact Information</h3>
                            <p><i class="fa fa-building"> 2nd Flr., Abalos Bldg., Aguinaldo St., Iligan City</i></p>
                            <p><i class="fa fa-phone-square"> 063-222-5370</i></p>
                            <p><i class="fa fa-fax"> 063-222-5123</i></p>
                            <p><i class="fa fa-envelope-square"> support@megamitch.com</i></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="footer">
    <div class="inner">
        <div class="container-fluid">
			<div class="row">
                <div class="col-lg-12">
                    <span class="footer-links">Copyright &copy; 2012-<?php echo date('Y') ?> by <a href="<?php echo $this->url('home') ?>">Mega Mitch Credit, Inc.</a> <?php echo $this->translate('All rights reserved.') ?></span>
                </div>
			</div> <!-- /row -->
			
        </div> <!-- /container -->
    </div>
</div>
